### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by darrenmce** [meet-tarantino/tarantino#14]
Parent Issue, see label "OSX Support"

**Comment by mpareja** [comment]
@StuartJSquires identified that the eval / declare hashtable approach from PR #9 doesn't work in Bash 3 used on Mac:

> Unfortunately, `declare` is a bash 4 feature, and osx uses bash 3 because GPL reasons.

**Comment by darrenmce** [comment]
closed in favour of a milestone
